// <auto-generated />
using System;
using GetStartedWithEFCoreInAspNetMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GetStartedWithEFCoreInAspNetMVC.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20220808023507_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GetStartedWithEFCoreInAspNetMVC.Models.CustomerAggregate.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"), 1L, 1);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customer", (string)null);

                    b.HasData(
                        new
                        {
                            CustomerID = 25,
                            DateOfBirth = new DateTime(2002, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Family = "azizi",
                            Name = "farshid"
                        },
                        new
                        {
                            CustomerID = 50,
                            DateOfBirth = new DateTime(2009, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Family = "amiri",
                            Name = "reza"
                        },
                        new
                        {
                            CustomerID = 75,
                            DateOfBirth = new DateTime(1983, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Family = "naseri",
                            Name = "amir"
                        },
                        new
                        {
                            CustomerID = 100,
                            DateOfBirth = new DateTime(2000, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Family = "emadi",
                            Name = "shirin"
                        },
                        new
                        {
                            CustomerID = 125,
                            DateOfBirth = new DateTime(2005, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Family = "tehrani",
                            Name = "maryam"
                        });
                });

            modelBuilder.Entity("GetStartedWithEFCoreInAspNetMVC.Models.OrderAggregate.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"), 1L, 1);

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrderState")
                        .HasColumnType("int");

                    b.HasKey("OrderID");

                    b.ToTable("Order", (string)null);

                    b.HasData(
                        new
                        {
                            OrderID = 1,
                            CustomerID = 25,
                            OrderDate = new DateTime(2022, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderState = 0
                        },
                        new
                        {
                            OrderID = 2,
                            CustomerID = 50,
                            OrderDate = new DateTime(2022, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderState = 0
                        });
                });

            modelBuilder.Entity("GetStartedWithEFCoreInAspNetMVC.Models.OrderAggregate.OrderItem", b =>
                {
                    b.Property<int>("OrderItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemID"), 1L, 1);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.HasKey("OrderItemID");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");

                    b.HasData(
                        new
                        {
                            OrderItemID = 1,
                            Count = 1,
                            OrderId = 1,
                            Price = 1000m,
                            ProductID = 10
                        },
                        new
                        {
                            OrderItemID = 2,
                            Count = 2,
                            OrderId = 1,
                            Price = 63520m,
                            ProductID = 60
                        },
                        new
                        {
                            OrderItemID = 3,
                            Count = 3,
                            OrderId = 2,
                            Price = 490m,
                            ProductID = 100
                        });
                });

            modelBuilder.Entity("GetStartedWithEFCoreInAspNetMVC.Models.ProductAggregate.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductID");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            ProductID = 10,
                            Description = "",
                            Name = "productA",
                            Price = 1000m
                        },
                        new
                        {
                            ProductID = 20,
                            Description = "",
                            Name = "productB",
                            Price = 36000m
                        },
                        new
                        {
                            ProductID = 30,
                            Description = "",
                            Name = "productC",
                            Price = 65200m
                        },
                        new
                        {
                            ProductID = 40,
                            Description = "",
                            Name = "productD",
                            Price = 1500m
                        },
                        new
                        {
                            ProductID = 50,
                            Description = "",
                            Name = "productE",
                            Price = 14000m
                        },
                        new
                        {
                            ProductID = 60,
                            Description = "",
                            Name = "productF",
                            Price = 63520m
                        },
                        new
                        {
                            ProductID = 100,
                            Description = "",
                            Name = "productG",
                            Price = 500m
                        });
                });

            modelBuilder.Entity("GetStartedWithEFCoreInAspNetMVC.Models.OrderAggregate.Order", b =>
                {
                    b.OwnsOne("GetStartedWithEFCoreInAspNetMVC.Models.OrderAggregate.Address", "Address", b1 =>
                        {
                            b1.Property<int>("OrderID")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Plaq")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OrderID");

                            b1.ToTable("Order");

                            b1.WithOwner()
                                .HasForeignKey("OrderID");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("GetStartedWithEFCoreInAspNetMVC.Models.OrderAggregate.OrderItem", b =>
                {
                    b.HasOne("GetStartedWithEFCoreInAspNetMVC.Models.OrderAggregate.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("GetStartedWithEFCoreInAspNetMVC.Models.OrderAggregate.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
